<?php

/**
 * Bulk add posts
 */
acf_add_local_field_group( array(
	'key'                   => 'acf_wtvr_bulk_add_post_group',
	'title'                 => 'Bulk add posts',
	'fields'                => array(
		array(
			'key'               => 'acf_wtvr_bulk_add_post_type',
			'label'             => 'Post type',
			'name'              => 'bulk_post_type',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
		),
		array(
			'key'               => 'acf_wtvr_bulk_add_post_source',
			'label'             => 'Source',
			'name'              => 'bulk_posts_source',
			'type'              => 'select',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'manual' => 'Manual',
				'json'   => 'JSON',
			),
			'allow_null'        => 0,
			'other_choice'      => 0,
			'default_value'     => 'manual',
			'layout'            => 'vertical',
			'return_format'     => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key'                           => 'acf_wtvr_bulk_add_posts',
			'label'                         => 'Posts',
			'name'                          => 'bulk_posts',
			'type'                          => 'repeater',
			'instructions'                  => '',
			'required'                      => 0,
			'conditional_logic'             => array(
				array(
					array(
						'field'    => 'acf_wtvr_bulk_add_post_source',
						'operator' => '==',
						'value'    => 'manual',
					),
				),
			),
			'wrapper'                       => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'collapsed'                     => '',
			'min'                           => 0,
			'max'                           => 0,
			'layout'                        => 'block',
			'button_label'                  => '',
			'sub_fields'                    => array(
				array(
					'key'               => 'acf_wtvr_bulk_add_title',
					'label'             => 'Title',
					'name'              => 'title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'acf_wtvr_bulk_add_subtitle',
					'label'             => 'Subtitle',
					'name'              => 'subtitle',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'acf_wtvr_bulk_add_link',
					'label'             => 'Link',
					'name'              => 'link',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'acf_wtvr_bulk_add_image',
					'label'             => 'Image',
					'name'              => 'image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'acf_wtvr_bulk_add_summary',
					'label'             => 'Summary',
					'name'              => 'summary',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'acf_wtvr_bulk_add_content',
					'label'             => 'Content',
					'name'              => 'content',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
			),
		),
		array(
			'key'                => 'acf_wtvr_bulk_add_content_json',
			'label'              => 'JSON code',
			'name'               => 'bulk_posts_json',
			'type'               => 'textarea',
			'instructions'       => '',
			'required'           => 0,
			'conditional_logic'  => [
				[
					[
						'field'    => 'acf_wtvr_bulk_add_post_source',
						'operator' => '==',
						'value'    => 'json',
					],
				],
			],
			'wrapper'            => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'      => '',
			'placeholder'        => '',
			'maxlength'          => '',
			'rows'               => 20,
			'new_lines'          => '',
			'acfe_textarea_code' => 0,
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'options_page',
				'operator' => '==',
				'value'    => 'acf-options-bulk-add-content',
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'seamless',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen'        => '',
	'active'                => true,
	'description'           => '',
	'acfe_display_title'    => '',
	'acfe_autosync'         => '',
	'acfe_form'             => 0,
	'acfe_meta'             => '',
	'acfe_note'             => '',
) );
